apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubernetes-linter.fullname" . }}
  labels:
    {{- include "kubernetes-linter.labels" . | nindent 4 }}
    release: dnation-kubernetes-monitoring-stack
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      relabelings:
      - action: replace
        regex: ^(.*)$
        replacement: $1
        separator: ;
        sourceLabels:
        - __meta_kubernetes_pod_container_name
        targetLabel: container
      targetPort: 9102
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kubernetes-linter.selectorLabels" . | nindent 6 }}
