apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  name: linter-servicemonitor
  labels:
    release: dnation-kubernetes-monitoring-stack
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      relabelings:
      - action: replace
        regex: ^(.*)$
        replacement: $1
        separator: ;
        sourceLabels:
        - __meta_kubernetes_pod_container_name
        targetLabel: container
      targetPort: 9102
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app_kubernetes_io: kubernetes-linter

