#
# Copyright 2021 The dNation Kubernetes Linter Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Lint and Test Chart

on:
  pull_request:
    # Only if there are chart changes to test.
    paths:
    - 'chart/**'
  workflow_dispatch:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Run chart-testing (lint)
      uses: helm/chart-testing-action@v1.0.0
      with:
        command: lint
        config: .github/ct.yaml

  build-image-install-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.17.11
          - v1.19.1
    needs:
      - lint-chart
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/
        file: ./docker/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: false
        load: true
        tags: dnationcloud/kubernetes-linter:test
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Create kind ${{ matrix.k8s }} cluster
      uses: helm/kind-action@v1.0.0
      with:
        node_image: kindest/node:${{ matrix.k8s }}

    - name: Load image
      run: |
        cluster_name=$(kind get clusters | head -1)
        kind load docker-image dnationcloud/kubernetes-linter:test --name $cluster_name

    - name: Run chart-testing (install)
      uses: helm/chart-testing-action@v1.0.0
      with:
        command: install
        config: .github/ct.yaml
